# Generated by Django 2.2 on 2019-04-24 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(null=True)),
                ('subject', models.TextField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('phone', models.FloatField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration',
                'db_table': 'user_registration',
            },
        ),
        migrations.CreateModel(
            name='CompanyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('jobpost', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Registration',
                'db_table': 'company_registration',
            },
        ),
    ]
