# Generated by Django 2.2 on 2019-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='age',
        ),
        migrations.AddField(
            model_name='userregister',
            name='certification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='fathername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='photo',
            field=models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/userphoto'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload only .txt, .pdf & .word file extension.', null=True, upload_to='image/userresume'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='zipcode',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
