# Generated by Django 2.2 on 2019-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_auto_20190502_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
