# Generated by Django 2.2 on 2019-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_auto_20190504_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobnotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(null=True)),
                ('jobdesignation', models.TextField(max_length=200, null=True)),
                ('joblocation', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Job notification',
                'db_table': 'Job_notification',
            },
        ),
    ]
