# Generated by Django 2.2 on 2019-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_jobnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(null=True)),
                ('candidate_skills', models.TextField(max_length=200, null=True)),
                ('candidate_location', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Candidate notification',
                'db_table': 'Candidate_notification',
            },
        ),
        migrations.RenameField(
            model_name='jobnotification',
            old_name='jobdesignation',
            new_name='job_designation',
        ),
        migrations.RenameField(
            model_name='jobnotification',
            old_name='joblocation',
            new_name='job_location',
        ),
    ]
