# Generated by Django 2.2 on 2019-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_auto_20190505_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_notification',
            name='candidate_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_notification',
            name='candidate_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_notification',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
