# Generated by Django 2.2 on 2019-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_auto_20190505_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Job Post',
                'db_table': 'Job_Post',
            },
        ),
    ]
