# Generated by Django 2.2 on 2019-05-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_job_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobnotification',
            old_name='job_designation',
            new_name='job_skills',
        ),
    ]
