# Generated by Django 2.2 on 2019-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_auto_20190506_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='post_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
